version: "3.7"
services:
  db:
    image: mysql:8.4
    container_name: MySQLdb
    command:
      - --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
    volumes:
      - ./mysqldb:/var/lib/mysql
      - ./src/main/resources/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"
    networks:
      - mynet
  rest-ws:
    image: bank-image
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bank
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/bank
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge